apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chart.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "chart.name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}

      containers:
        - name: main-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 80

          {{- if  .Values.readiness  }}
          readinessProbe:
            {{- toYaml .Values.readiness | nindent 12 }}
          {{- end }}

          {{- if  .Values.liveness  }}
          livenessProbe:
            {{- toYaml .Values.liveness | nindent 12 }}
          {{- end }}

          {{- if  .Values.startup  }}
          startupProbe:
            {{- toYaml .Values.startup  | nindent 12 }}
          {{- end }}

          envFrom:
            - configMapRef:
                name: {{ include "chart.fullname" . }}
